version: "1"
services:
  nginx-react:
    container_name: react-nginx-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      NODE_ENV: production
